name: opt
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.9.0
  - pip:
    - absl-py
    - accelerate
    - aiohttp
    - aiosignal
    - async-timeout
    - attrs
    - best-download
    - black
    - chardet
    - click
    - colorama
    - cycler
    - cython
    - dataproperty
    - datasets
    - dill
    - dynet38
    - einops
    - filelock
    - fonttools
    - frozenlist
    - fsspec
    - hjson
    - huggingface-hub
    - iniconfig
    - jieba
    - joblib
    - jsonlines
    - kiwisolver
    - lm-dataformat
    - matplotlib
    - mbstrdecoder
    - mock
    - msgfy
    - multidict
    - multiprocess
    - mypy-extensions
    - nagisa
    - ninja
    - nltk   
    - numexpr
    - packaging    
    - pandas
    - pathspec
    - pathvalidate
    - platformdirs
    - pluggy
    - portalocker
    - psutil
    - py
    - py-cpuinfo
    - pyarrow
    - pycountry
    - pydantic
    - pyparsing
    - pytablewriter
    - pytest
    - python-dateutil
    - pytz
    - pyyaml   
    - regex
    - rehash
    - responses
    - rouge-score
    - sacrebleu
    - scikit-learn
    - scipy
    - seaborn
    - sqlitedict
    - tabledata
    - tabulate
    - tcolorpy
    - threadpoolctl
    - tokenizers==0.12
    - toml
    - tomli
    - torchsummary
    - tqdm
    - tqdm-multiprocess
    - tueplots
    - typepy
    - ujson
    - xxhash
    - yarl
    - zstandard
